# Generated by Django 2.1.5 on 2019-01-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='書名')),
                ('price', models.PositiveIntegerField(verbose_name='價格')),
            ],
        ),
    ]
