# Generated by Django 2.1.4 on 2018-12-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_introduction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='introduction',
            field=models.TextField(verbose_name='簡介'),
        ),
        migrations.AlterField(
            model_name='book',
            name='name',
            field=models.CharField(max_length=20, verbose_name='書名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveIntegerField(verbose_name='價錢'),
        ),
    ]
